
import java.sql.DriverManager;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author daniel
 */
public class Search_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Search_GUI
     */
    public Search_GUI() {
        initComponents();
        //show_ap();
    }
    
    public ArrayList<appartment> aplist(){
        ArrayList<appartment> apList = new ArrayList<>() ;
    try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url;
        
        url = "jdbc:sqlserver://localhost:1433;databaseName=Second;user=omar;password=11798";
        Connection con = DriverManager.getConnection(url);
        String query = "Select * From dbo.Apartments";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        appartment ap ;
        while(rs.next())
        {
          //  ap = new appartment(rs.getString("Renter_Name") , rs.getString("Address") , rs.getString("Area") , rs.getString("Description") , rs.getInt("Mates_No"), rs.getInt("price"));
        //    apList.add(ap);
        }
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
    return apList ;
}
    /*
        public ArrayList<appartment> Searced_aplist(String searched_area){
        ArrayList<appartment> apList = new ArrayList<>() ;
    try {
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
        String url;
        
        url = "jdbc:sqlserver://localhost:1433;databaseName=Second;user=omar;password=11798";
        Connection con = DriverManager.getConnection(url);
        String query = "Select * From dbo.Apartments where Area=?";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, searched_area);
        ResultSet rs = pst.executeQuery();
        appartment ap ;
        while(rs.next())
        {
            ap = new appartment(rs.getString("Renter_Name") , rs.getString("Address") , rs.getString("Area") , rs.getString("Description") , rs.getInt("Mates_No"), rs.getInt("price"));
            apList.add(ap);
        }
    }
    catch (Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
    return apList ;
}*/
    // To show all of the data in apartement table 
    /*
    public void show_ap(){
        ArrayList<appartment> list = aplist() ;
        DefaultTableModel model = (DefaultTableModel) Apartments_list.getModel();
        Object[] row = new Object[6] ;
        for (int i=0 ; i<list.size() ; i++)
        {
            row[0] = list.get(i).getRenter_Name() ;
            row[1] = list.get(i).getAddress();
            row[2] = list.get(i).getArea() ;
            row[3] = list.get(i).getDescription() ;
            row[4] = list.get(i).getMates_No() ;
            row[5] = list.get(i).getPrice() ;
            model.addRow(row);
        
    }
    }*/
    
    // To show the list of searched apartements using the function Searced_aplist from User class 
    public void show_searced()
    {
        User us = new User();
      //  ArrayList<appartment> list  = us.Searced_aplist (Area_cmb.getSelectedItem().toString()) ;
        DefaultTableModel model = (DefaultTableModel) Apartments_list.getModel();
        Object[] row = new Object[6] ;
//        for (int i=0 ; i<list.size() ; i++)
        {
            /*
            row[0] = list.get(i).getRenter_Name() ;
            row[1] = list.get(i).getAddress();
            row[2] = list.get(i).getArea() ;
            row[3] = list.get(i).getDescription() ;
            row[4] = list.get(i).getMates_No() ;
            row[5] = list.get(i).getPrice() ;
            model.addRow(row);
            */
    }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Apartments_list = new javax.swing.JTable();
        Area_cmb = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        Search_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        Apartments_list.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Apartments_list.setForeground(new java.awt.Color(51, 51, 51));
        Apartments_list.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Renter", "Address", "Area", "Description", "Mates No", "Price"
            }
        ));
        jScrollPane1.setViewportView(Apartments_list);

        Area_cmb.setBackground(new java.awt.Color(0, 0, 0));
        Area_cmb.setEditable(true);
        Area_cmb.setFont(new java.awt.Font("Berlin Sans FB", 1, 14)); // NOI18N
        Area_cmb.setForeground(new java.awt.Color(31, 116, 206));
        Area_cmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Helwan", "El-Zamalek", "El-Agoza", "Mokattam", "Dokki" }));
        Area_cmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Area_cmbActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Area");

        Search_btn.setBackground(new java.awt.Color(0, 0, 0));
        Search_btn.setFont(new java.awt.Font("Berlin Sans FB", 1, 18)); // NOI18N
        Search_btn.setForeground(new java.awt.Color(255, 255, 255));
        Search_btn.setText("Search");
        Search_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Area_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(Search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 426, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Area_cmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(137, 137, 137)
                .addComponent(Search_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Search_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_btnActionPerformed
        // TODO add your handling code here:
       // String choosed_area = Area_cmb.getSelectedItem().toString();
        show_searced();

    }//GEN-LAST:event_Search_btnActionPerformed

    private void Area_cmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Area_cmbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Area_cmbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Search_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Search_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Search_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Search_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Search_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Apartments_list;
    private javax.swing.JComboBox<String> Area_cmb;
    private javax.swing.JButton Search_btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
